export const APPOINTMENT_FLOW = Object.freeze({
  REQUESTED: ['CONFIRMED', 'CANCELLED', 'NO_SHOW'],
  CONFIRMED: ['ARRIVED', 'CHECKED_IN', 'RESCHEDULED', 'CANCELLED', 'NO_SHOW'],
  ARRIVED: ['CHECKED_IN', 'WAITING', 'CANCELLED', 'NO_SHOW'],
  CHECKED_IN: ['WAITING', 'IN_CONSULTATION', 'CANCELLED', 'NO_SHOW'],
  WAITING: ['IN_CONSULTATION', 'CHECKED_IN', 'SKIPPED', 'CANCELLED', 'NO_SHOW'],
  IN_CONSULTATION: ['COMPLETED', 'CANCELLED', 'NO_SHOW'],
  COMPLETED: [],
  SKIPPED: ['WAITING', 'CHECKED_IN', 'CANCELLED', 'NO_SHOW'],
  CANCELLED: [],
  NO_SHOW: ['ARRIVED', 'CHECKED_IN', 'WAITING', 'IN_CONSULTATION', 'COMPLETED'],
  SCHEDULED: ['CONFIRMED', 'CANCELLED', 'NO_SHOW'],
  IN_PROGRESS: ['COMPLETED', 'CANCELLED'],
});