import { forwardRef } from 'react';
import { Printer } from 'lucide-react';
import { format } from 'date-fns';
import { cn } from '../lib/utils';

const HOSPITAL = {
  name: 'ZhanX Medical Centre',
  tagline: 'Multi-Speciality · NABH-towards · ICMR recognised lab',
  address: 'No. 14, Anna Salai, Chennai 600 002',
  phone: '+91 44 4000 2000',
  email: 'care@zhanx.health',
};

const fmtVal = (v) => {
  if (v === null || v === undefined || v === '') return '—';
  if (Array.isArray(v)) {
    const parts = v.map((i) => (i && typeof i === 'object' ? i.name || i.label || i.code || i.firstName || '' : String(i))).filter(Boolean);
    return parts.join(', ') || '—';
  }
  if (typeof v === 'object') {
    const pick = ['name', 'label', 'value', 'code', 'firstName', 'status', 'title'];
    for (const k of pick) if (v[k]) return String(v[k]);
    const flat = Object.values(v).filter((x) => x !== null && x !== undefined && typeof x !== 'object');
    return flat.join(' / ') || '—';
  }
  return String(v);
};

const ReportPrintSheet = forwardRef(function ReportPrintSheet({ title, subtitle, rows, printHeader, onPrint }, ref) {
  const cols = rows.length ? Object.keys(rows[0]) : [];
  const generatedAt = new Date();
  return (
    <div className="report-sheet">
      <div className="flex items-center justify-between gap-4 border-b-2 border-ink-900 pb-3">
        <div className="flex items-center gap-3">
          <div className="flex h-12 w-12 items-center justify-center rounded-full bg-brand-700 text-lg font-black text-white">Z</div>
          <div>
            <h1 className="text-lg font-black leading-tight text-ink-900">{HOSPITAL.name}</h1>
            <p className="text-[10px] font-medium uppercase tracking-widest text-brand-700">{HOSPITAL.tagline}</p>
          </div>
        </div>
        <div className="text-right text-[10px] leading-tight text-ink-500">
          <p>{HOSPITAL.address}</p>
          <p>{HOSPITAL.phone} · {HOSPITAL.email}</p>
        </div>
      </div>

      <div className="mt-3 text-center">
        <h2 className="text-base font-extrabold uppercase tracking-wide text-ink-900">{title}</h2>
        <p className="text-xs text-ink-500">{subtitle}{printHeader ? ` · ${printHeader}` : ''}</p>
      </div>

      <div className="mx-auto mt- pic-4 table-wrap">
        <table className="w-full border-collapse">
          <thead>
            <tr>
              <th className="border border-ink-300 bg-ink-100 px-2 py-1.5 text-left text-[10px] font-bold uppercase tracking-wide text-ink-800">#</th>
              {cols.map((c) => (
                <th key={c} className="border border-ink-300 bg-ink-100 px-2 py-1.5 text-left text-[10px] font-bold uppercase tracking-wide text-ink-800">
                  {c.replace(/([A-Z])/g, ' $1').replace(/[._]/g, ' ')}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((r, i) => (
              <tr key={i}>
                <td className="border border-ink-300 px-2 py-1 text-[10px] text-ink-600">{i + 1}</td>
                {cols.map((c) => (
                  <td key={c} className="border border-ink-300 px-2 py-1 text-[10px] text-ink-800">{fmtVal(r[c])}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-4 flex items-end justify-between">
        <div className="text-[10px] text-ink-500">
          <p>Generated: {format(generatedAt, 'dd MMM yyyy HH:mm')}</p>
          <p>Generated by: {printHeader ? printHeader.split(' · ').pop() : ''}</p>
          <p>Row count: {rows.length}</p>
        </div>
        <div className="text-center text-[10px]">
          <div className="mb-8 h-10 border-b border-ink-300 w-36" />
          <p className="font-semibold text-ink-900">Authorised Signatory</p>
          <p className="text-ink-500">Lab / Department In-charge</p>
        </div>
      </div>
    </div>
  );
});

export default ReportPrintSheet;
