import { Router } from 'express';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import patientRoutes from './patient.routes.js';
import masterRoutes from './master.routes.js';
import appointmentRoutes from './appointment.routes.js';
import opdRoutes from './opd.routes.js';
import ipdRoutes from './ipd.routes.js';
import ipdWorkflowRoutes from './ipd.workflow.routes.js';
import ipdBillingRoutes from './ipd.billing.routes.js';
import ipdTransferRoutes from './ipd.transfer.routes.js';
import pharmacyRoutes from './pharmacy.routes.js';
import labRoutes from './lab.routes.js';
import radiologyRoutes from './radiology.routes.js';
import billingRoutes from './billing.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import reportRoutes from './report.routes.js';
import notificationRoutes from './notification.routes.js';
import auditRoutes from './audit.routes.js';
import cashierRoutes from './cashier.routes.js';
import insuranceRoutes from './insurance.routes.js';
import settingsRoutes from './setting.routes.js';
import operationalRoutes from './operational.routes.js';
import searchRoutes from './search.routes.js';
import queueRoutes from './queue.routes.js';
import moduleRoutes from './module.routes.js';
import platformRoutes from './platform.routes.js';
import dialysisRoutes from './dialysis.routes.js';

const router = Router();

router.use(platformRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/patients', patientRoutes);
router.use('/masters', masterRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/opd', opdRoutes);
router.use('/ipd', ipdRoutes);
router.use('/ipd', ipdWorkflowRoutes);
router.use('/ipd', ipdBillingRoutes);
router.use('/ipd', ipdTransferRoutes);
router.use('/dialysis', dialysisRoutes);
router.use('/pharmacy', pharmacyRoutes);
router.use('/lab', labRoutes);
router.use('/radiology', radiologyRoutes);
router.use('/billing', billingRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/reports', reportRoutes);
router.use('/notifications', notificationRoutes);
router.use('/audit', auditRoutes);
router.use('/settings', settingsRoutes);
router.use('/operations', operationalRoutes);
router.use('/search', searchRoutes);
router.use('/queue', queueRoutes);
router.use('/cashier', cashierRoutes);
router.use('/insurance', insuranceRoutes);
router.use('/modules', moduleRoutes);

export default router;